version: '3'

services:

  app:
    container_name: app
    build:
      context: node
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    ports:
      - "3000:3000"

  db:
    container_name: db
    image: mysql:5.7
    command: --innodb_use_native_aio=0
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=node_db
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
