version: '3'

services:

  app:
    container_name: app
    build:
      context: node
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s sh -c "npm install && npm run dev"
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - db

  db:
    container_name: db
    build: ./db_setup
    restart: always
    tty: true
    volumes:
      - ./db_setup/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=node_db
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  nginx:
    container_name: nginx
    build:
      context: nginx
    ports:
      - "8080:80"
    networks:
      - node-network
    depends_on:
      - app

networks:
  node-network:
    driver: bridge

volumes:
  mysql:
    driver: local
